<?php
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php
    $theme = $this->helper('fortis');
	$_helper = $this->helper('catalog/product_compare');
	$count = $_helper->getItemCount();
	$_items = $count > 0 ? $_helper->getItemCollection() : null;

   	if ($count > 0)
	{
		$mainTitle = $this->__('Compare Products');
	}
	else
	{
		$mainTitle = $this->__('You have no items to compare.');
	}

    //Icon color suffix
    $colorString = $theme->getCfgDesign('header/icon_color');
    $iconSuffix = ($colorString == 'b') ? '' : '-'.$colorString;
?>

<div id="quick-compare" class="dropdown quick-compare<?php echo (!$count ? ' is-empty' : ' is-not-empty'); ?>">

    <div class="dropdown-toggle cover" title="<?php echo $mainTitle; ?>">
    	<div class="feature-icon-hover umi-border-bottom">
        	<span class="first close-to-text force-no-bg-color icon i-compare<?php echo $iconSuffix; ?>">&nbsp;</span>
	        <div class="name"><?php echo $this->__('Compare'); ?></div>
			<?php if($count > 0): ?>
            	<a class="umi-amount amount" href="#" title="<?php echo $this->__('Compare all selected items') ?>" onclick="popWin('<?php echo $_helper->getListUrl(); ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?php echo $this->__('(%d)', $count); ?></a>
			<?php else: ?>
            	<div class="umi-amount amount">(0)</div>
			<?php endif; ?>
            <span class="caret">&nbsp;</span>
        </div>
    </div>
    <div class="dropdown-menu left-hand">
    <?php if($count > 0): ?>
    	<h4 class="block-subtitle"><?php echo $this->__('Recently added item(s)'); ?></h4>
        <ol id="compare-items">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><?php echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
            <button type="button" title="<?php echo $this->__('Compare Products') ?>" class="button btn-inline" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
    <?php else: ?>
        <div class="empty"><?php echo $this->__('You have no items to compare.') ?></div>
    <?php endif; ?>
    </div><!-- end: dropdown-menu -->

</div>







<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

?>
<?php if ($this->getIsNeedToDisplaySideBar()): ?>
<?php
	$theme = $this->helper('fortis');
	$_cartQty = $this->getSummaryCount();
   	if ($_cartQty > 0)
	{
		$mainTitle = $this->__('View Cart');
	}
	else
	{
		$mainTitle = $this->__('You have no items in your shopping cart.');
	}

    //Icon color suffix
    $colorString = $theme->getCfgDesign('header/icon_color');
    $iconSuffix = ($colorString == 'b') ? '' : '-'.$colorString;

	$cartClasses = '';
	if (!$_cartQty)
	{
		$cartClasses .= ' is-empty';
		if ($theme->getCfg('header/hide_on_mobile'))
		{
			$cartClasses .= ' hide-empty-cart';
		}
	}
	else
	{
		$cartClasses .= ' is-not-empty';
	}
?>

<div id="mini-cart" class="dropdown<?php echo $cartClasses; ?>">

    <div class="dropdown-toggle cover" title="<?php echo $mainTitle; ?>">
        <div class="feature-icon-hover">
    
    	<span class="first close-to-text force-no-bg-color icon i-cart<?php echo $iconSuffix; ?>">&nbsp;</span>
        <div class="name"><?php echo $this->__('Cart'); ?></div>
		<?php if ($_cartQty > 0): ?>
        	<div class="label amount umi-price">(<?php echo $_cartQty; ?>)</div>
        	<a class="summary umi-price" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View all items in your shopping cart') ?>">
                <span class="subtotal">
					<?php if ($this->canApplyMsrp()): ?>
                    	<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                    <?php else: ?>
						<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()); ?>
                    <?php endif; ?>
				</span>
			</a>
        <?php else: //no products ?>
        	<div class="empty umi-price"><?php echo Mage::helper('checkout')->formatPrice(0); ?></div>
        <?php endif; ?>
        <span class="caret">&nbsp;</span>

        </div> <!-- end: dropdown-toggle > div -->
    </div> <!-- end: dropdown-toggle -->
    
    <?php $_items = $this->getRecentItems(); ?>
    <?php if (count($_items)): ?>
    	<div class="dropdown-menu left-hand">
        	<div class="">

				<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                	<span class="incl-tax">(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)</span>
                <?php endif; ?>
                
				<?php if ($tmpHtml = $this->getChildHtml('block_mini_cart_above_products')): ?> <?php //Predefined CMS block ?>
                    <div class="block_mini_cart_above_products"><?php echo $tmpHtml; ?></div>
                <?php endif; ?>
            
                <h4 class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></h4>
                <ol id="cart-sidebar" class="mini-products-list clearer">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
                </ol>
                <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                
                <div class="actions clearer">
                    <button type="button" title="<?php echo $this->__('View all items in your shopping cart') ?>" class="button btn-inline" onclick="setLocation('<?php echo $this->getUrl('checkout/cart') ?>')"><span><span><?php echo $this->__('View All') ?></span></span></button>
                    
                    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                    	<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-checkout btn-inline " onclick="setLocation('<?php echo $this->getCheckoutUrl(); ?>')"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
						<?php echo $this->getChildHtml('extra_actions') ?>
                    <?php endif; ?>
                </div>

			</div> <!-- end: block-content-inner -->
        </div> <!-- end: dropdown-menu -->
    <?php else: ?>
    	<div class="dropdown-menu left-hand block">
        	<div class="block-content-inner">

				<?php if ($tmpHtml = $this->getChildHtml('block_mini_cart_above_products')): ?>
                    <div class="block_mini_cart_above_products"><?php echo $tmpHtml; ?></div>
                <?php endif; ?>
                <div class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></div>

            </div> <!-- end: block-content-inner -->
		</div> <!-- end: dropdown-menu -->
    <?php endif ?>

</div> <!-- end: mini-cart -->

<?php endif;?>




