<?php 
    $_order = $this->getOrder();
    $_shipMethod = $_order->getShippingMethod();
    $disallowShippingMethods4Date = explode(' ', $this->helper('deliverydate')->getDisallowShippingMethods4Date());
    $disallowShippingMethods4Time = explode(' ', $this->helper('deliverydate')->getDisallowShippingMethods4Time());
    $_ddHelper = Mage::helper('deliverydate');
?>
<div class="box-left">
    <!--Delivery Date-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('deliverydate')->__('Delivery Information') ?></h4>
            <?php if (Mage::helper('deliverydate')->canEditDeliveryDateTime($_order)): ?>
            <div class="tools">
                <a class="dd-view" href="#" onclick="return showEditForm()"><?php echo $this->__('Edit') ?></a>
            </div>
            <?php endif ?>
        </div>
        <div class="fieldset">
            <div id="dd_msg"></div>
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('deliverydate')->__('Delivery Date') ?></label></td>
                <td class="value">
                    <div class="dd-view">
                        <strong id="delivery_date_label"><?php echo $_order->getDeliveryDate() ?></strong>
                    </div>
                    <?php if ($this->helper('deliverydate')->isShowDeliveryDate() && !in_array($_shipMethod, $disallowShippingMethods4Date)): ?>
                    <div class="dd-form" style="display:none;">
                        <?php echo $this->helper('deliverydate')->getDeliveryDateInline(); ?>
                    </div>
                    <?php endif ?>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('deliverydate')->__('Delivery Time') ?></label></td>
                <td class="value">
                    <div class="dd-view">
                        <strong id="delivery_time_label"><?php echo $_order->getDeliveryTime() ?></strong>
                    </div>
                    <?php if ($this->helper('deliverydate')->isShowDeliveryTime() && !in_array($_shipMethod, $disallowShippingMethods4Time)): ?>
                    <div class="dd-form" style="display:none;">
                        <?php echo $this->helper('deliverydate')->getDeliveryTimeInline(); ?>
                    </div>
                    <?php endif ?>
                </td>
            </tr>
            <tr class="dd-form" style="display:none;">
                <td></td>
                <td class="value">
                    <button class="scalable back" onClick="hideEditForm();hideError();" type="button"><span><?php echo $this->__('Cancel') ?></span></button>
                    <button class="scalable" onClick="saveDdForm()" type="button"><span><?php echo $this->__('Save') ?></span></button>
                </td>
            </tr>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>
<script type="text/javascript">
    <?php if ($_ddHelper->isUseCalendar()): ?>
    var lastDeliveryDate = '<?php echo $_ddHelper->convertDateToIntStyle($_order->getDeliveryDate())?>';
    <?php endif ?>

    function showEditForm() {
        $$('.dd-view').each(function(el) { el.hide(); });
        $$('.dd-form').each(function(el) { el.show(); });

        <?php if ($_ddHelper->isUseCalendar()): ?>
        deliveryDateCalendar.selection.set(lastDeliveryDate);
        <?php else: ?>
        if ($('delivery_date')) {
            $('delivery_date').value = $('delivery_date_label').innerHTML;
        }
        <?php endif ?>
        if ($('delivery_time')) {
            $('delivery_time').value = $('delivery_time_label').innerHTML;
        }
        return false;
    }
    
    function hideEditForm() {
        $$('.dd-view').each(function(el) { el.show(); });
        $$('.dd-form').each(function(el) { el.hide(); });
        
        return false;
    }
    
    function hideError() {
        $('dd_msg').hide();
    }
    
    function updateLabel() {
        if ($('delivery_date')) {
            $('delivery_date_label').innerHTML = $('delivery_date').value;
        }
        if ($('delivery_time')) {
            $('delivery_time_label').innerHTML = $('delivery_time').value;
        }
    }
    
    function saveDdForm() {
        var url = '<?php echo $this->getUrl('adminhtml/deliverydate/update') ?>';
        var ddParams = $H({});
        if ($('delivery_date')) {
            ddParams.set('delivery_date', $('delivery_date').value);
        }
        if ($('delivery_time')) {
            ddParams.set('delivery_time', $('delivery_time').value);
        }
        ddParams.set('order_id', '<?php echo $_order->getId() ?>')
        new Ajax.Request(url, {
            method: 'post',
            parameters: ddParams,
            onSuccess: function(response) {
                var data = response.responseText;
                if (data.isJSON()) {
                    var result = data.evalJSON();
                    if (result.success == true) {
                        showMessage('success-msg', result.message, true);
                        updateLabel();
                        hideEditForm();

                        <?php if ($_ddHelper->isUseCalendar()): ?>
                        lastDeliveryDate = result.deliveryDate;
                        <?php endif ?>
                    } else {
                        showMessage('error-msg', result.message, false);
                    }
                }
            }
        });
    }
    
    function showMessage(type, msg, autoHide) {
        var html = '<ul class="messages"><li class="' + type + '"><ul><li><span>' + msg + '</span></li></ul></li></ul>';
        $('dd_msg').update(html);
        $('dd_msg').show();
        if (autoHide == true) {
            setTimeout(function(){
                $('dd_msg').fade();
            }, 3000);
        }
    }
</script>